name: Build and Deploy Landing App
on:
  push:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: "${{ github.sha}}:0:7"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          registry: registry.malefstorm.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USERPASSWORD }}
      - name: Shorten SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Print short SHA
        run: echo ${{ env.SHORT_SHA }}