name: Build and Deploy Landing App
on:
  push:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: "${{ github.sha}}:0:7"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          registry: registry.malefstorm.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USERPASSWORD }}

      - name: Shorten SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            registry.malefstorm.ru/malefstudio/landing:${{ env.SHORT_SHA }}
            registry.malefstorm.ru/malefstudio/landing:latest

      - name: Ckecjout k8s app
        uses: actions/checkout@v6
        with:
          repository: LeoEliot/kubernetes
          token: ${{ secrets.PAT_TOKEN }}
      - name: Edit and commit
        run: |
          cd apps/landing/overlays/prod
          sed -i 's|newTag: .*|newTag: ${{ env.SHORT_SHA }}'
          git add .
          git config --local user.email "vakkfuder@gmail.com"
          git config --local user.name "Auto Commit"
          git commit -am "Update Image tag to ${{ env.SHORT_SHA }}"
          git push -u origin main